using System;
using System.Collections.Generic;
using System.IO;

namespace SFD.Scripting.Resources.Generator;

public sealed class Sounds : IGenerator
{
    public string GeneratedSource => "Sounds.generated.cs";
    public string[] DirectoriesWhitelist => ["Sounds"];
    public string[] IgnoredFiles => [];

    public void Generate(string dataRoot, string outputDir)
    {
        string dbPath = Path.Combine(dataRoot, DirectoriesWhitelist[0], "Sounds.sfds");
        if (!File.Exists(dbPath))
        {
            Console.Error.WriteLine($"Sounds database not found: '{dbPath}'");
            return;
        }

        string output = Path.Combine(outputDir, GeneratedSource);
        using CodeWriter writer = new(output);
            writer.WriteLine("""
                             // <auto-generated>This file was generated by the SFD.Scripting.Resources generator. Do not edit manually.</auto-generated>

                             using SFDGameScriptInterface;

                             namespace SFD.Scripting.Resources;

                             public partial class GameScript : GameScriptInterfaceExtended
                             {
                             """);
        writer.IncrementPadding();

        writer.WriteLine("""
                             public static class SoundsDatabase
                             {
                             """);
        writer.IncrementPadding();

        string[] lines = File.ReadAllLines(dbPath);

        HashSet<string> ignored = [.. IgnoredFiles];
        HashSet<string> seen = [];

        foreach (string line in lines)
        {
            string trimmed = line.Trim();
            if (trimmed.Length == 0 || trimmed[0] == '/') continue;

            int space = trimmed.IndexOf(' ');
            string name = space < 0 ? trimmed : trimmed[..space];

            if (name.Length == 0 || ignored.Contains(name)) continue;

            string identifier = name.Replace("_", string.Empty);
            if (!seen.Add(identifier))
            {
                Console.Error.WriteLine($"Duplicate sound '{name}' skipped.");
                continue;
            }

            writer.WriteLine($"public const string {identifier} = \"{name}\";");
        }

        writer.DecrementPadding();
        writer.WriteLine("}");

        writer.DecrementPadding();
        writer.WriteLine("}");
    }
}
