using System.IO;
using System.Linq;

namespace SFD.Scripting.Resources.Generator;

public sealed class Tiles : IGenerator
{
    public string GeneratedSource => "Tiles.generated.cs";
    public string[] DirectoriesWhitelist => ["Images/Tiles", "Images/Objects"];
    public string[] IgnoredFiles => [];

    public void Generate(string dataRoot, string outputDir)
    {
        string[] directories = [.. DirectoriesWhitelist.Select(d => Path.Combine(dataRoot, d))];

        string output = Path.Combine(outputDir, GeneratedSource);
        using CodeWriter writer = new(output);
            writer.WriteLine("""
                             // <auto-generated>This file was generated by the SFD.Scripting.Resources generator. Do not edit manually.</auto-generated>

                             using SFDGameScriptInterface;

                             namespace SFD.Scripting.Resources;

                             public partial class GameScript : GameScriptInterfaceExtended
                             {
                             """);
        writer.IncrementPadding();

        writer.WriteLine("""
                             public static class TilesDatabase
                             {
                             """);
        writer.IncrementPadding();

        foreach (string file in Directory.GetFiles(directories, "*.png", SearchOption.AllDirectories))
        {
            string fileName = Path.GetFileNameWithoutExtension(file);
            if (Enumerable.Contains(IgnoredFiles, fileName)) continue;
            writer.WriteLine($"public const string {fileName.Replace("_", string.Empty)} = \"{fileName}\";");
        }

        writer.DecrementPadding();
        writer.WriteLine("}");

        writer.DecrementPadding();
        writer.WriteLine("}");
    }
}
